// <auto-generated />
using System;
using GameOverDose.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameOverDose.DAL.Migrations
{
    [DbContext(typeof(GameOverDoseDbContext))]
    [Migration("20251215220426_SomeMigration")]
    partial class SomeMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameOverDose.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("commentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("gameid");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("CommentId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("idx_comment_gameid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_comment_userid");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("userid1");

                    b.Property<int>("UserId2")
                        .HasColumnType("integer")
                        .HasColumnName("userid2");

                    b.HasKey("Id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("idx_friend_userid1");

                    b.HasIndex("UserId2")
                        .HasDatabaseName("idx_friend_userid2");

                    b.HasIndex("UserId1", "UserId2")
                        .IsUnique()
                        .HasDatabaseName("idx_friend_users");

                    b.ToTable("friend", null, t =>
                        {
                            t.HasCheckConstraint("CK_Friend_DifferentUsers", "userid1 <> userid2");
                        });
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Added")
                        .HasColumnType("integer")
                        .HasColumnName("added");

                    b.Property<string>("AddedByStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("added_by_status");

                    b.Property<string>("BackgroundImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("background_image");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_text");

                    b.Property<string>("EsrbRating")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("esrb_rating");

                    b.Property<int?>("Metacritics")
                        .HasColumnType("integer")
                        .HasColumnName("metacritics");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platforms");

                    b.Property<int?>("Playtime")
                        .HasColumnType("integer")
                        .HasColumnName("playtime");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<int?>("RatingTop")
                        .HasColumnType("integer")
                        .HasColumnName("rating_top");

                    b.Property<string>("Ratings")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ratings");

                    b.Property<int?>("RatingsCount")
                        .HasColumnType("integer")
                        .HasColumnName("ratings_count");

                    b.Property<int?>("RatingsTop")
                        .HasColumnType("integer")
                        .HasColumnName("ratings_top");

                    b.Property<DateTime?>("Release")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("release");

                    b.Property<int?>("RewiewsTextCount")
                        .HasColumnType("integer")
                        .HasColumnName("rewiews_text_count");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int?>("SuggestionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("suggestions_count");

                    b.Property<bool>("Tba")
                        .HasColumnType("boolean")
                        .HasColumnName("tba");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("trailer_url");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("Rating")
                        .HasDatabaseName("idx_games_rating");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_games_slug");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("Lvl")
                        .HasColumnType("integer")
                        .HasColumnName("lvl");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasDatabaseName("idx_users_nickname");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("gameid");

                    b.Property<int>("Hours")
                        .HasColumnType("integer")
                        .HasColumnName("hours");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<bool>("IsTracking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tracking");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_played");

                    b.Property<int?>("PersonalRating")
                        .HasColumnType("integer")
                        .HasColumnName("personal_rating");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .HasDatabaseName("idx_usergame_gameid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_usergame_userid");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("idx_usergame_user_game");

                    b.ToTable("usergame", (string)null);
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.Comment", b =>
                {
                    b.HasOne("GameOverDose.DAL.Entities.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOverDose.DAL.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.Friend", b =>
                {
                    b.HasOne("GameOverDose.DAL.Entities.User", "User1")
                        .WithMany("FriendsAsUser1")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameOverDose.DAL.Entities.User", "User2")
                        .WithMany("FriendsAsUser2")
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.UserGame", b =>
                {
                    b.HasOne("GameOverDose.DAL.Entities.Game", "Game")
                        .WithMany("UserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOverDose.DAL.Entities.User", "User")
                        .WithMany("UserGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.Game", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UserGames");
                });

            modelBuilder.Entity("GameOverDose.DAL.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FriendsAsUser1");

                    b.Navigation("FriendsAsUser2");

                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
